# Generated by Django 5.2.9 on 2026-04-02 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(80, message='Описание слишком короткое (минимум 80 символов).')], verbose_name='Описание'),
        ),
    ]
