# Generated by Django 5.2.9 on 2026-04-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ad_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='currency',
            field=models.CharField(choices=[('UZS', 'сум'), ('USD', '$')], default='UZS', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена'),
        ),
    ]
