# Generated by Django 5.2.9 on 2026-04-02 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_ad_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(80, message='Минимум 80 символов')], verbose_name='Описание'),
        ),
    ]
