# Generated by Django 5.2.9 on 2026-04-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_alter_ad_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='Контактный номер'),
            preserve_default=False,
        ),
    ]
